version: '3'

services: 
  
  nginx:
   image: nginx:alpine
   container_name: server_nginx
   restart: unless-stopped
   volumes:
   - "./app:/app"
   - "./default.conf:/etc/nginx/conf.d/default.conf"
   ports:
   - "8080:80"
#LEMBRE-SE SEMPRE DE CRIAR OS ARQUIVOSSSSS

  php:
   image: php:7.3-fpm
   container_name: php_container
   restart: unless-stopped
   volumes: 
    - "/.default.conf:/etc/php/"
   ports:
    - "9000:9000"

  laravel:
    image: eboraas/laravel
    container_name: laravel_container
    restart: unless-stopped
     